<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
کنکلی
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مقدمه و صورت مسئله
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در این تمرین قصد داریم پیش‌بینی کنیم آیا کاربران بلیط خود را کنسل می‌کنند یا نه. به ازای هر کنسلی، مستربلیط باید به شرکت مسافربری جریمه پرداخت کند! پس بلیط‌های    کنسلی به معنی تحمیل هزینه به شرکت است. از این رو تشخیص دادن بلیط‌هایی که احتمال کنسلی آنان وجود دارد، به مدیریت ریسک شرکت کمک بزرگی می‌کند. 
    <br>
    حال از داده‌هایی که در اختیارتان قرار گرفته است استفاده کنید و مدلی آموزش دهید که کنسل شدن یا نشدن سفر را تشخیص دهد.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
وارد کردن کتابخانه‌های مورد نیاز
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    ابتدا کتابخانه‌های مورد نیازتان را وارد کنید.
</font>
</p>

In [1]:
import pandas as pd
import numpy as np

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معرفی مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
مجموعه داده آموزشی شامل ۱۰۱۰۱۷ سطر است که در جدول زیر، توضیحات هر ستون آمده است.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|Created|زمان ثبت بلیط|
|CancelTime|زمانی که مسافر بلیط را کنسل کرده است|
|DepartureTime|زمان حرکت|
|BillID|شناسه خرید|
|TicketID|شناسه بلیط|
|ReserveStatus|وضعیت پرداخت مشتری|
|UserID|شناسه کاربری|
|Male|آیا بلیط متعلق به زن است یا مرد|
|Price|قیمت بلیط بدون تخفیف|
|CouponDiscount|تخفیفی که شخص روی بلیط اعمال کرده است|
|From|مبدا سفر|
|To|مقصد سفر|
|Domestic|آیا سفر، داخلی است یا خارجی|
|VehicleType|جزئیات وسیله نقلیه را مشخص می‌کند|
|VehicleClass|آیا وسیله نقلیه، فرست‌کلس است یا نه|
|Vehicle|نوع وسیله نقلیه|
|HashPassportNumber_p|هش‌شده شماره پاسپورت|
|HashEmail|هش‌شده ایمیل|
|BuyerMobile|هش‌شده شماره موبایل|
|NationalCode|هش‌شده شماره‌ملی|
|TripReason|دلیل سفر|
|Cancel|آیا بلیط کنسل شده‌است یا نه|
    
</font>
</div>
</center>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    مجموعه داده آزمایش نیز مانند مجموعه آموزش است با این تفاوت که ستون <code>Cancel</code> که متغیر هدف مسئله است را در خود ندارد. مجموعه داده آزمایش ۴۳۲۹۳ سطر دارد.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
خواندن مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در ابتدا نیاز است فایل‌های مجموعه‌داده را بخوانید. نمونه‌های آموزشی در فایل <code>train_data.csv</code> و نمونه‌های آزمون که باید دسته‌ی آن‌ها را پیش‌بینی کنید در فایل <code>test_data.csv</code> ذخیره شده‌اند. اگر لازم دانستید می‌توانید به دلخواه خود بخشی از مجموعه داده آموزشی را به عنوان مجموعه داده اعتبارسنجی نیز جدا کنید.
</font>
</p>

In [9]:
train_data = pd.read_csv('../data/train_data.csv')

In [10]:
test_data = pd.read_csv('../data/test_data.csv')

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
پیش‌پردازش و مهندسی ویژگی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در این سوال شما می‌توانید از هر تکنیک پیش‌پردازش/مهندسی ویژگی که در فصل‌های گذشته آموختید، استفاده کنید.
    <br>
    تکنیک‌هایی که استفاده می‌کنید به شکل مستقیم مورد ارزیابی توسط سامانه داوری قرار <b>نمی‌گیرند.</b> بلکه همه آن‌ها در دقت مدل شما تاثیر خواهند گذاشت؛ بنابراین هر چه پیش‌پردازش/مهندسی ویژگی بهتری انجام دهید تا دقت مدل بهبود پیدا کند، امتیاز بیشتری از این سوال کسب خواهید کرد.
</font>
</p>

In [ ]:
train_data.isna().sum()

In [11]:
train_data['Created'] = pd.to_datetime(train_data['Created'],format="ISO8601")
test_data['Created'] = pd.to_datetime(test_data['Created'],format="ISO8601")

train_data['DepartureTime'] = pd.to_datetime(train_data['DepartureTime'],format="ISO8601")
test_data['DepartureTime'] = pd.to_datetime(test_data['DepartureTime'],format="ISO8601")

train_data['TimeDifference'] = (train_data['DepartureTime'] - train_data['Created']).dt.days
test_data['TimeDifference'] = (test_data['DepartureTime'] - test_data['Created']).dt.days

In [12]:
# do some preprocessing 
train_data.drop(['CancelTime','VehicleType','UserID','HashPassportNumber_p','HashEmail','BuyerMobile','CouponDiscount','BillID','TicketID','NationalCode'],axis=1,inplace=True)
missing_mask = train_data['VehicleClass'].isna()
fill_mask = train_data[missing_mask].sample(frac=0.75, random_state=42).index
train_data.loc[fill_mask, 'VehicleClass'] = True
remaining_mask = missing_mask & ~train_data.index.isin(fill_mask)
train_data.loc[remaining_mask, 'VehicleClass'] = False

test_data.drop(['VehicleType','UserID','HashPassportNumber_p','HashEmail','BuyerMobile','CouponDiscount','BillID','TicketID','NationalCode'],axis=1,inplace=True)
missing_mask = test_data['VehicleClass'].isna()
fill_mask = test_data[missing_mask].sample(frac=0.75, random_state=42).index
test_data.loc[fill_mask, 'VehicleClass'] = True
remaining_mask = missing_mask & ~test_data.index.isin(fill_mask)
test_data.loc[remaining_mask, 'VehicleClass'] = False

cols_to_encode = list(train_data.drop(['ReserveStatus','Price','Domestic','Cancel','Created','DepartureTime'],axis=1).columns)

In [13]:
from sklearn.preprocessing import OrdinalEncoder
from hazm import Normalizer

normalizer = Normalizer()
train_data['From'] = train_data['From'].apply(normalizer.normalize)
test_data['From'] =test_data['From'].apply(normalizer.normalize)
train_data['To'] = train_data['To'].apply(normalizer.normalize)
test_data['To'] = test_data['To'].apply(normalizer.normalize)

encoder = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
train_encoded = encoder.fit_transform(train_data[cols_to_encode])
test_encoded = encoder.transform(test_data[cols_to_encode])

train_data[cols_to_encode] = train_encoded
test_data[cols_to_encode] = test_encoded

In [14]:
train_data['Created_month'] = train_data['Created'].dt.month
train_data['Created_day'] = train_data['Created'].dt.day
train_data['Departure_month'] = train_data['DepartureTime'].dt.month
train_data['Departure_day'] = train_data['DepartureTime'].dt.day

test_data['Created_month'] = test_data['Created'].dt.month
test_data['Created_day'] = test_data['Created'].dt.day
test_data['Departure_month'] = test_data['DepartureTime'].dt.month
test_data['Departure_day'] = test_data['DepartureTime'].dt.day

train_data.drop(['Created','DepartureTime'],axis=1,inplace=True)
test_data.drop(['Created','DepartureTime'],axis=1,inplace=True)

In [15]:
train_data

,ReserveStatus,Male,Price,From,To,Domestic,VehicleClass,TripReason,Vehicle,Cancel,TimeDifference,Created_month,Created_day,Departure_month,Departure_day
0,3,1.0,1180000.0,134.0,155.0,1,1.0,1.0,0.0,0,0.0,7,26,7,26
1,5,0.0,1050000.0,150.0,138.0,1,1.0,0.0,0.0,1,1.0,10,27,10,29
2,5,0.0,4674000.0,67.0,19.0,1,0.0,0.0,2.0,0,21.0,9,12,10,3
3,3,1.0,1200000.0,67.0,220.0,1,1.0,1.0,0.0,0,0.0,8,8,8,8
4,5,1.0,6222000.0,200.0,76.0,1,0.0,1.0,2.0,0,1.0,11,1,11,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101012,2,0.0,7200000.0,167.0,76.0,1,1.0,0.0,3.0,0,8.0,10,27,11,5
101013,2,0.0,4292000.0,167.0,28.0,1,1.0,0.0,3.0,0,26.0,9,24,10,21
101014,3,1.0,1320000.0,134.0,28.0,1,1.0,0.0,0.0,0,0.0,8,12,8,12
101015,5,1.0,13000000.0,67.0,132.0,1,0.0,1.0,2.0,0,4.0,6,20,6,25
101016,3,1.0,2150000.0,18.0,76.0,1,1.0,1.0,0.0,0,0.0,7,25,7,25

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مدل‌سازی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    حال که داده را پاکسازی کرده و احتمالا ویژگی‌هایی را به آن افزوده یا از آن حذف کرده‌اید، وقت آن است که مدلی آموزش دهید که بتواند متغیر هدف این مسئله را پیش‌بینی کند.
    <br>
    بر خلاف سایر تمرین‌های کالج، در این تمرین شما مجاز هستید از هر مدلی که آموخته‌اید استفاده کنید. به عبارت بهتر، هدف این سوال پیش‌بینی هرچه بهتر متغیر هدف مسئله است. انتظار ما این است که نحوه کار با کتابخانه‌های یادگیری ماشین را در حدی آموخته باشید که بتوانید با بهترین عملکرد، مسئله را حل کنید!
</font>
</p>

In [38]:
from sklearn.model_selection import train_test_split

X_train,X_val,y_train,y_val = train_test_split(train_data.drop(['Cancel'],axis=1),train_data['Cancel'],test_size =.2,random_state=42)

In [40]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=50,max_depth=20,oob_score=False)
model.fit(X_train,y_train)
y_pred = model.predict(X_val)

TypeError: Cannot cast DatetimeArray to dtype float32

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معیار ارزیابی
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    معیاری که برای ارزیابی عملکرد مدل انتخاب کرده‌ایم، <code>f1_score</code> نام دارد.
    <br>
    این معیار، سنجه ارزیابی کیفیت مدل شماست. به عبارت بهتر در سامانه داوری هم از همین معیار برای نمره‌دهی استفاده شده است.
    <br>
    پیشنهاد می‌شود با توجه به این معیار، عملکرد مدل خود را بر روی مجموعه داده آموزش یا اعتبارسنجی ارزیابی کنید.
</font>
</p>

In [32]:
# evaluate model
from sklearn.metrics import f1_score, classification_report, confusion_matrix
print('f1 score : ',f1_score(y_val,y_pred))

f1 score :  0.9514049586776859

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font color="red"><b color='red'>توجه:</b></font>
<font face="vazir" size=3>
 جهت کسب امتیاز کامل نیاز است تا پاسخ شما حداقل امتیاز <code>95%</code> را با توجه به معیار معرفی‌شده کسب نماید.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
 پیش‌بینی برای داده تست و خروجی
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    پس از مهندسی ویژگی و مدلسازی، الگوریتمی دارید که می‌تواند شما را از متغیرهای مستقل به متغیر هدف برساند.
    <br>
    از این مدل برای پیش‌بینی نمونه‌های موجود در داده تست استفاده کنید و نتایج را در قالب جدول (<code>dataframe</code>) زیر آماده کنید.
</font>
</p>

<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|------|---|
|Cancel|آیا بلیط کنسل می‌شود یا نه|
    
</font>
</div>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    اسم دیتافریم باید <code>submission</code> باشد؛ در غیر این صورت، سامانه داوری نمی‌تواند تلاش‌ شما را ارزیابی کند.
    <br>
    این دیتافریم تنها شامل ۱ ستون با اسم <i>Cancel</i> است و ۴۳۲۹۳ سطر دارد.
    <br>
    به ازای هر سطر موجود در دیتافریم <i>test</i> شما باید یک مقدار پیشبینی شده داشته باشید.
    <br>
    جدول زیر، ۵ سطر ابتدایی دیتافریم <code>submission</code> را نشان می‌دهد. البته در جواب شما، مقادیر ستون <i>Cancel</i> ممکن است متفاوت باشد.
</font>
</p>

<div style="text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
||Cancel|
|----|-----|
|0|0|
|1|0|
|2|1|
|3|1|
|4|0|

</font>
</div>

In [7]:
# predict test samples
submission = pd.DataFrame({'Cancel':model.predict(test_data)})
submission

Empty DataFrame
Columns: []
Index: []

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [8]:
import zipfile
import joblib

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)
            
submission.to_csv('submission.csv', index=False)
file_names = ['canceli.ipynb', 'submission.csv']
compress(file_names)

File Paths:
['canceli.ipynb', 'submission.csv']