<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
نام تمرین
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مقدمه و صورت مسئله
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    ...
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
وارد کردن کتابخانه‌های مورد نیاز
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    ابتدا کتابخانه‌های مورد نیازتان را وارد کنید.
</font>
</p>

In [1]:
import numpy as np
import pandas as pd 
import scipy.sparse as ss

from sklearn.svm import SVC
from sklearn.decomposition import PCA
from sklearn.metrics import classification_report, f1_score

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معرفی مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
...    
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|DateTime|زمان ثبت رکورد|
|Junction|شماره چهارراه|
|Car|تعداد ماشین‌های گذرکرده|
    
</font>
</div>
</center>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    توضیحات اضافه
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
خواندن مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در ابتدا نیاز است فایل‌های مجموعه‌داده را بخوانید. نمونه‌های آموزشی در فایل <code>train.csv</code> و نمونه‌های آزمون که باید دسته‌ی آن‌ها را پیش‌بینی کنید در فایل <code>test.csv</code> ذخیره شده‌اند. اگر لازم دانستید می‌توانید به دلخواه خود بخشی از دادگان آموزشی را به عنوان دادگان اعتبارسنجی نیز جدا کنید.
</font>
</p>

In [2]:
train_data = pd.read_csv('../data/news_train.csv')
train_data_text_vectors = ss.load_npz('../data/news_train_text_vectors.npz')

test_data = pd.read_csv('../data/news_test.csv')
test_data_text_vectors = ss.load_npz('../data/news_test_text_vectors.npz')

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
پیش‌پردازش و مهندسی ویژگی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در این سوال شما می‌توانید از هر تکنیک پیش‌پردازش/مهندسی ویژگی که در فصل‌های گذشته آموختید، استفاده کنید.
    <br>
    تکنیک‌هایی که استفاده می‌کنید به شکل مستقیم مورد ارزیابی توسط سامانه داوری قرار <b>نمی‌گیرند.</b> بلکه همه آن‌ها در دقت مدل شما تاثیر خواهند گذاشت؛ بنابراین هر چه پیش‌پردازش/مهندسی ویژگی بهتری انجام دهید تا دقت مدل بهبود پیدا کند، امتیاز بیشتری از این سوال کسب خواهید کرد.
</font>
</p>

In [3]:
train_data_text_vectors = pd.DataFrame(train_data_text_vectors.toarray(),\
                                  columns = ['token' + str(i) for i in range(train_data_text_vectors.shape[1])] )

train_data_text_vectors

,token0,token1,token2,token3,token4,token5,token6,token7,token8,token9,...,token42131,token42132,token42133,token42134,token42135,token42136,token42137,token42138,token42139,token42140
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1496,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1497,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1498,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1499,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
test_data_text_vectors = pd.DataFrame(test_data_text_vectors.toarray(),\
                                  columns = ['token' + str(i) for i in range(test_data_text_vectors.shape[1])] )

test_data_text_vectors

,token0,token1,token2,token3,token4,token5,token6,token7,token8,token9,...,token42131,token42132,token42133,token42134,token42135,token42136,token42137,token42138,token42139,token42140
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
341,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
342,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
343,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
344,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
345,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
from sklearn.model_selection import train_test_split
train , validation = train_test_split(train_data, random_state=313, \
                                                   stratify=train_data.label)

In [6]:
train_text_vectors = train_data_text_vectors.loc[train.index]
valid_text_vectors = train_data_text_vectors.loc[validation.index]

In [7]:
class Preprocessor : 
    def __init__ (self, ) : 
             pass 
            
    def detect_suspicious_site_urls(self, thresh = 0.5) :
        site_url_status = self.df.replace({'label': {'Fake':1, 'Real':0}}).groupby('site_url').label.agg('mean')
        suspicious_sites = site_url_status[site_url_status >= thresh].index.tolist()
        not_suspicious_sites = site_url_status[site_url_status < thresh].index.tolist()
        
        return suspicious_sites, not_suspicious_sites
    
    def detect_suspicious_types(self, thresh = 0.5) : 
        type_status = self.df.replace({'label': {'Fake':1, 'Real':0}}).groupby('type').label.agg('mean')
        suspicious_types = type_status[type_status >= thresh].index.tolist()
        not_suspicious_types = type_status[type_status < thresh].index.tolist()
        
        return suspicious_types, not_suspicious_types
    
    def detect_suspicious_authors(self, thresh= 0.5) :  
        author_status = self.df.replace({'label': {'Fake':1, 'Real':0}}).groupby('author').label.agg('mean')
        suspicious_authors = author_status[author_status >= thresh].index.tolist()
        not_suspicious_authors = author_status[author_status < thresh].index.tolist()
        
        return suspicious_authors, not_suspicious_authors
    
    def transform(self, dataframe: pd.DataFrame, is_train=False) :   
        self.df = dataframe.copy()
        
        if is_train : 
            self.suspicious_sites , self.not_suspicious_sites = self.detect_suspicious_site_urls()
            self.suspicious_types, self.not_suspicious_types = self.detect_suspicious_types()
            self.suspicious_authors, self.not_suspicious_authors = self.detect_suspicious_authors()
              
        if not is_train and (not hasattr(self, 'suspicious_sites') or not hasattr(self, 'suspicious_types') \
                            or not hasattr(self, 'suspicious_authors')) : 
            raise AttributeError('suspicious fields required! call `tranform` method with `is_train` param set to True')
        
        self.df['is_site_url_suspicious'] = None 
        self.df.loc[self.df.site_url.isin(self.suspicious_sites), 'is_site_url_suspicious'] = 1 
        self.df.loc[self.df.site_url.isin(self.not_suspicious_sites), 'is_site_url_suspicious'] = -1
        self.df.is_site_url_suspicious.fillna(0, inplace=True)
        
        
        self.df['is_type_suspicious'] = None 
        self.df.loc[self.df.type.isin(self.suspicious_types), 'is_type_suspicious'] = 1 
        self.df.loc[self.df.type.isin(self.not_suspicious_types), 'is_type_suspicious'] = -1
        self.df.is_type_suspicious.fillna(0, inplace=True)
        
        
        self.df['is_author_suspicious'] = None 
        self.df.loc[self.df.author.isin(self.suspicious_authors), 'is_author_suspicious'] = 1 
        self.df.loc[self.df.author.isin(self.not_suspicious_authors), 'is_author_suspicious'] = -1
        self.df.is_author_suspicious.fillna(0, inplace=True)
        
        self.df.drop(['author', 'published', 'site_url', 'type'], axis=1, inplace=True)
        
        return self.df

In [8]:
preprocessor = Preprocessor()

In [9]:
preproccesed_train = preprocessor.transform(train, is_train=True)
preproccesed_valid = preprocessor.transform(validation,)

/var/folders/cx/2jf76yxd4gs0c7ts38kcldh80000gn/T/ipykernel_1270/365971915.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  site_url_status = self.df.replace({'label': {'Fake':1, 'Real':0}}).groupby('site_url').label.agg('mean')
/var/folders/cx/2jf76yxd4gs0c7ts38kcldh80000gn/T/ipykernel_1270/365971915.py:13: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  type_status = self.df.replace({'label': {'Fake':1, 'Real':0}}).groupby('type').label.agg('mean')
/var/folders/cx/2jf76yxd4gs0c7ts38kcldh80000gn/T/ipykernel_1270/365971915.py:20: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  author_status = self.df.replace({'label': {'Fake':1, 'Real':0}}).groupby('author').label.agg('mean')
/var/folders/cx/2jf76yxd4gs0c7ts38kcldh80000gn/T/ipykernel_1270/365971915.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.df.is_site_url_suspicious.fillna(0, inplace=True)
/var/folders/cx/2jf76yxd4gs0c7ts38kcldh80000gn/T/ipykernel_1270/365971915.py:47: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.df.is_type_suspicious.fillna(0, inplace=True)
/var/folders/cx/2jf76yxd4gs0c7ts38kcldh80000gn/T/ipykernel_1270/365971915.py:53: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.df.is_author_suspicious.fillna(0, inplace=True)
/var/folders/cx/2jf76yxd4gs0c7ts38kcldh80000gn/T/ipykernel_1270/365971915.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.df.is_site_url_suspicious.fillna(0, inplace=True)
/var/folders/cx/2jf76yxd4gs0c7ts38kcldh80000gn/T/ipykernel_1270/365971915.py:41: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.df.is_site_url_suspicious.fillna(0, inplace=True)
/var/folders/cx/2jf76yxd4gs0c7ts38kcldh80000gn/T/ipykernel_1270/365971915.py:47: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.df.is_type_suspicious.fillna(0, inplace=True)
/var/folders/cx/2jf76yxd4gs0c7ts38kcldh80000gn/T/ipykernel_1270/365971915.py:53: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.df.is_author_suspicious.fillna(0, inplace=True)
/var/folders/cx/2jf76yxd4gs0c7ts38kcldh80000gn/T/ipykernel_1270/365971915.py:53: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.df.is_author_suspicious.fillna(0, inplace=True)

In [10]:
preproccesed_train

     label is_site_url_suspicious is_type_suspicious is_author_suspicious
1164  Real                     -1                 -1                   -1
16    Real                     -1                 -1                   -1
772   Fake                      1                  1                    1
946   Fake                      1                  1                    1
1031  Real                     -1                 -1                   -1
...    ...                    ...                ...                  ...
400   Real                     -1                 -1                   -1
1383  Fake                      1                  1                    1
667   Fake                      1                  1                    1
1297  Real                     -1                 -1                   -1
752   Fake                      1                  1                    1

[1125 rows x 4 columns]

In [11]:
dr = PCA(n_components=500)
reduced_train_text_vectors = dr.fit_transform(train_text_vectors)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مدل‌سازی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    حال که داده را پاکسازی کرده و احتمالا ویژگی‌هایی را به آن افزوده یا از آن حذف کرده‌اید، وقت آن است که مدلی آموزش دهید که بتواند متغیر هدف این مسئله را پیش‌بینی کند.
</font>
</p>

<h3 align=right style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    استفاده از <code>scikit-learn</code>
</font>
</h3>


<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|پارامتر|توضیحات|
|------|---|
|fit_intercept|زمان ثبت رکورد|
|degree|شماره چهارراه|
|max_depth|تعداد ماشین‌های گذرکرده|
    
</font>
</div>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    ...
</font>
</p>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
آموزش مدل
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در سلول زیر با استفاده از مدل آماده‌ای که در بالا شرح داده شد و به کمک تابع <code>fit</code> الگوریتم را بر روی دادگان آموزشی اجرا کنید.
</font>
</p>

In [12]:
text_model = SVC()

text_model.fit(reduced_train_text_vectors, preproccesed_train.label)

SVC()

In [13]:
y_pred = text_model.predict(dr.transform(valid_text_vectors))

In [14]:
from sklearn.metrics import classification_report, f1_score

print(f1_score(preproccesed_valid.label, y_pred, average='weighted'))
print(classification_report(preproccesed_valid.label, y_pred))

0.7318620792174876
              precision    recall  f1-score   support

        Fake       0.85      0.71      0.77       247
        Real       0.57      0.76      0.65       128

    accuracy                           0.73       375
   macro avg       0.71      0.73      0.71       375
weighted avg       0.76      0.73      0.73       375

In [15]:
preproccesed_train['label_from_text_model'] = text_model.predict(reduced_train_text_vectors)
preproccesed_train.label_from_text_model.replace({
    "Real": 0,
    "Fake" : 1
}, inplace=True)
preproccesed_train

/var/folders/cx/2jf76yxd4gs0c7ts38kcldh80000gn/T/ipykernel_1270/116903789.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  preproccesed_train.label_from_text_model.replace({
/var/folders/cx/2jf76yxd4gs0c7ts38kcldh80000gn/T/ipykernel_1270/116903789.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  preproccesed_train.label_from_text_model.replace({

,label,is_site_url_suspicious,is_type_suspicious,is_author_suspicious,label_from_text_model
1164,Real,-1,-1,-1,0
16,Real,-1,-1,-1,0
772,Fake,1,1,1,1
946,Fake,1,1,1,1
1031,Real,-1,-1,-1,1
...,...,...,...,...,...
400,Real,-1,-1,-1,0
1383,Fake,1,1,1,1
667,Fake,1,1,1,1
1297,Real,-1,-1,-1,0
752,Fake,1,1,1,1

In [16]:
model = SVC()
model.fit(preproccesed_train.drop('label', axis=1), preproccesed_train.label)

SVC()

In [17]:
preproccesed_valid['label_from_text_model'] = text_model.predict(dr.transform(valid_text_vectors))
preproccesed_valid.label_from_text_model.replace({
    "Real": 0,
    "Fake" : 1
}, inplace=True)
preproccesed_valid

/var/folders/cx/2jf76yxd4gs0c7ts38kcldh80000gn/T/ipykernel_1270/896928864.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  preproccesed_valid.label_from_text_model.replace({
/var/folders/cx/2jf76yxd4gs0c7ts38kcldh80000gn/T/ipykernel_1270/896928864.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  preproccesed_valid.label_from_text_model.replace({

,label,is_site_url_suspicious,is_type_suspicious,is_author_suspicious,label_from_text_model
388,Fake,1,1,1,1
413,Real,-1,-1,0,1
745,Fake,1,1,1,0
383,Real,-1,-1,-1,0
11,Fake,1,1,1,0
...,...,...,...,...,...
639,Real,-1,-1,0,1
822,Fake,1,1,1,1
1462,Fake,1,1,1,0
474,Real,-1,-1,1,0
1066,Fake,1,1,1,1

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معیار ارزیابی
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    معیاری که برای ارزیابی عملکرد مدل انتخاب کرده‌ایم، <code>f1_score</code> نام دارد.
    <br>
    این معیار، سنجه ارزیابی کیفیت مدل شماست. به عبارت بهتر در سامانه داوری هم از همین معیار برای نمره‌دهی استفاده شده است.
    <br>
    پیشنهاد می‌شود با توجه به این معیار، عملکرد مدل خود را بر روی دادگان آموزش یا اعتبارسنجی ارزیابی کنید.
</font>
</p>

In [18]:
y_pred = model.predict(preproccesed_valid.drop('label', axis=1))

In [19]:
print(f1_score(preproccesed_valid.label, y_pred, average='weighted'))
print(classification_report(preproccesed_valid.label, y_pred))

1.0
              precision    recall  f1-score   support

        Fake       1.00      1.00      1.00       247
        Real       1.00      1.00      1.00       128

    accuracy                           1.00       375
   macro avg       1.00      1.00      1.00       375
weighted avg       1.00      1.00      1.00       375

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font color="red"><b color='red'>توجه:</b></font>
<font face="vazir" size=3>
 جهت کسب امتیاز کامل نیاز است تا پاسخ شما حداقل امتیاز <code>80</code> را با توجه به معیار معرفی‌شده کسب نماید.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
 پیش‌بینی برای داده تست و خروجی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    پس از مهندسی ویژگی و مدل‌سازی، الگوریتمی دارید که می‌تواند شما را از متغیرهای مستقل به متغیر هدف برساند.
    <br>
    از این مدل برای پیش‌بینی نمونه‌های موجود در داده تست استفاده کنید و نتایج را در قالب جدول زیر آماده کنید.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|DateTime|زمان ثبت رکورد|
|Junction|شماره چهارراه|
|Car|تعداد ماشین‌های گذرکرده|
    
</font>
</div>
</center>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    توضیحات اضافه
</font>
</p>

In [20]:
preproccessed_test = preprocessor.transform(test_data)


preproccessed_test['label_from_text_model'] = text_model.predict(dr.transform(test_data_text_vectors))


preproccessed_test.label_from_text_model.replace({
    "Real": 0,
    "Fake" : 1
}, inplace=True)

preproccessed_test

/var/folders/cx/2jf76yxd4gs0c7ts38kcldh80000gn/T/ipykernel_1270/365971915.py:41: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.df.is_site_url_suspicious.fillna(0, inplace=True)
/var/folders/cx/2jf76yxd4gs0c7ts38kcldh80000gn/T/ipykernel_1270/365971915.py:41: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.df.is_site_url_suspicious.fillna(0, inplace=True)
/var/folders/cx/2jf76yxd4gs0c7ts38kcldh80000gn/T/ipykernel_1270/365971915.py:47: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.df.is_type_suspicious.fillna(0, inplace=True)
/var/folders/cx/2jf76yxd4gs0c7ts38kcldh80000gn/T/ipykernel_1270/365971915.py:53: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.df.is_author_suspicious.fillna(0, inplace=True)
/var/folders/cx/2jf76yxd4gs0c7ts38kcldh80000gn/T/ipykernel_1270/365971915.py:53: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.df.is_author_suspicious.fillna(0, inplace=True)
/var/folders/cx/2jf76yxd4gs0c7ts38kcldh80000gn/T/ipykernel_1270/2205806376.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  preproccessed_test.label_from_text_model.replace({
/var/folders/cx/2jf76yxd4gs0c7ts38kcldh80000gn/T/ipykernel_1270/2205806376.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  preproccessed_test.label_from_text_model.replace({

,is_site_url_suspicious,is_type_suspicious,is_author_suspicious,label_from_text_model
0,-1,-1,-1,0
1,1,1,1,1
2,-1,-1,0,0
3,-1,-1,0,0
4,-1,-1,-1,1
...,...,...,...,...
341,1,1,1,1
342,-1,-1,-1,0
343,1,1,1,1
344,1,1,1,1
345,1,1,1,1

In [21]:
y_pred = model.predict(preproccessed_test)

In [ ]:
submission = pd.DataFrame(y_pred, columns=['label'])
submission

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [ ]:
import zipfile
import joblib

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

joblib.dump(model, 'model')
submission.to_csv('submission.csv', index=False)
file_names = ['fake_news_detection.ipynb', 'submission.csv', 'model']
compress(file_names)

<h4 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>راهنمایی</b>
</font>
</h4>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    ...
</font>
</p>